language: ruby

rvm:
 - 2.3.1p112

script:
 - bundle exec rake db:migrate --trace
 - RAILS_ENV=test bundle exec rake db:migrate --trace
 - bundle exec rake db:test:prepare
 - bundle exec rspec -fd spec/

 deploy:
   provider: heroku
   app: mysterious-shelf-55664
   api_key:
     secure: "GmDRqg4SAEazMoBTl23d68UIThDBhyy0sr+iv/J67/hau6dk2RdAy8dQsvK8ewdnvwuWU1RcDmbBu6dGdN3syl7IfPsID/btkJ2aW3xzY5zr4JHyNtAbuc7nm/rp/SpNiMY4qm/t18Z2bKnfC8rS/yWe/nGljYdV56MoFOdreFnwUZ/YMCwZm+Kj1kkntj1Y3nPlY3BjdDtHmVirSrp92CZGHpUTu7iaZxenNkMFCZq9craab00e0Q/fJSzKUMGdDKnFTtD+8qWrR1DNwyduQ3sxHra/+CKX3VBxT3i5nNS3Nrc0Jwt63zn9AzMZhT2tNCnFrjx3tLxNJ9MnpI9lNzHuI9XVrU/SXaTdsFd0UiM8jMB3Dp7LxSWIqVIHf5ICZbQzHHpF9jjKpLA3VyK+9SRlZPEEybL4mAAC6s9nXQAQESJmpxmaIDQAbGgUHs/gl57aKVeE+F8csdNibyrzLa5RNAAbrlPDKPxuJ9HElptF6u43qOkuuMQYSLY1Ymnc9GEbneI8hGWnbMtydipd1OJ1cEZqdV7yd84CSfxBpAN2bRUZUpA/1Ou5kd/eP7YaJkJ14/fk//RSiuDS8JV3Fbv0fF3Qv7cA/Ha0JBwbOxe9LeeVmA6S9Udc2jw0c6kTncojzeSCgW55g28sbYDgNWb6dD4jjZhnSDvwqcV0VTQ="
   run: "rake db:migrate"