language: ruby
rvm:
- 2.3.1
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
api_key:
  secure: hUVlRLOo1w0XBn8LJVmnm/Q1aYbA3cV0PrOm7yzaupgS3/NkUH8j18OP/Y/7Qx5+el9Jc/wiitA9w72f1xKTXq79WDWno2Iyuw4PoMzI3pSoI8kwh+lrbspkjxWkuCySgR7mdqXTf5kW8LTyULr+zMwRiD6KPqnqzBDhuqq/IJ/VbY7ECADBqCaNqBuyeTTsrj8KmxkAwWu3WVzHnF/LSFtLDUSPDUE45GaDYsq8gFZhsN8jM8Qs10kyec4oiHKgZ7Ziew9CaYMtXUahYGVb88PKr/G40bg1UYlqnFhrq4zsxD8qJcZB5Jqc2XPsu3uk3+m/HXcd4nQGoRUHXOX+EoKj7ad9XCPQW91X90dvHaPzXecfqaLH9iiP64W0v1RudisPM35JlYfTuZabYKSbdXEHjKPZU63Am85/DRIlFNGGSq5bby37M7f3+Jk6mVz37RLumdbdRHQEfXhYkAN901nK7VmRhXe0wYpFZG1oNzhCIarGxle5O3nO4vpI6hKdoP3Cg5bUPI9A59Ya3a8cXkKH+SQ/BJprnQeL2invnXOrgSNsRxuqp0yj5A5/pKDnKEC5oAAWUgZsjC9FEmPoroPNsHeLmrEqGWwIa6iRG5dmiH527S6olgqRAcSCWS5cSMa4ymREqEYKrhEm9nUDdmzlEy09JybmcR4tA6yz+Bw=
