language: ruby

rvm:
 - 2.3.1p112

script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/

deploy:
  provider: heroku
  api_key:
     secure: h4YEatKDq+KXa2uIYmr5rDE/5vAMef/WaAGdz7S6QDHMVFdKFUK5/qZGdS0d5ICrYujdxBR9Enn6n3SjeVzMOZ8WlBwa9qUYt5sVtfWZ+arqWgbAOZBJFBsEoXEI/G2rEeiJrzSc1NO+Cc3W4bgLCE/UcOtfskCXW76q/3c+O2E5FmeHRq0vT6AIlmhuXnwYIec+mgz4WOK43yfKGVw7ptAkrVbQMJRAQZXVRVOHxMYEd190nQ9gwz/0gqqjU2rmMzZQLwo1c2ywGA1Mun0qXqiFo2kkoH4yBQSfHHcQeI7EILFevD1fALvc/SLS/Tqpo7INK5VWSq56Dy56pFX7j+07d4kjnYSQfUxWmUikClR482AhtRy/FoSaJDfmo/pakbTEK5uL3JC8ZbRbTM4C9uOFL13rZPPPBYRxdrqlq3iPCQwYivoWrop6Bmj/C9soe3tuNQ0Yb8oXy2oCJYZ5k3CDPdNvtfexWQufoGjbWVWWL5r+ap6QAhl2OoFKgLYpf+FzNY9TlK0DawpjZqMKa76IePO3VsI+diXR/3Yq1Xaamwi8yRmRzamzXTkRDgyWKknuttCUKXB0z2OpOh3CEh1JWODkjjiiyRxOn4+0VhJktMrtiW8FKQzrt50v9R/mYiu4grI7uDl5aZP5OjTmEAddRshssGqo3WWLtVjPNlo=