language: ruby
rvm:
- 2.3.1
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: tXj/qyNXKUKR0OQfvZkAvggh8HeBsgMr3jBVInv17XJ96E+r01J3WDDLQ+/aDObd/f0x3OIxtigxCcAxR7LbqGr+ZV3MT7nOVScVn86mmCpHxseilWR3jxcf88YdMgD4r+ymzBfGYzW7PnapORpKxXC302R9hw5XRtZ8UI778I0PQzl6suBExxQy7lAXqhUxi7QRZ/38M8Cv6X5/2eOSgURYZkjj1z9gNRqcbvbBTcFLvc0KriKPZvlynxGDa3WhGXYJgZqGyJKC4HyILVgi8TDO9vd0RhQfbmKMZ5motaiWiTI26TuM8iOunnZfviYOkeBsrW+arWm6gtPh2hfq8mNt7fv9pLaSuAtMSKMdviH2/Te3OgXhXT50fhSVvI9WRUElCTXFV8H8NkCa1skEQlL4d/BXCbJKMiRpjpAeZG0FMX0sQuwTUDHVQLPu2Pqo0jHR+PtwMwAETIiyHfKt9coEly5uNxs9Q6w+X9kprsrE8CdUMT5yO9G6FI71Av22iD66rI/4+xxNaiqEPIXv2CeheEHOU35v0oFpTQ2603E6t43UeQgq3SJ7qhmWtCRGlHwm7wsBVSn+r1tiXPdVbNBeDKLdarlfCh/jaLO41YV4H7aYDhT4jETE0BQtzZFfnKh1fI7JpnrWzl5kyNMMnNMlwvqcMcSE9sJqbjouZ1c=
  app: mysterious-shelf-55664